export type CategorySlug =
  | "jogos-de-tabuleiro"
  | "roupas"
  | "moveis"
  | "sapatos"
  | "discos"
  | "objetos-gerais"
  | "cozinha"
  | "livros"
  | "eletronicos";

export interface Category {
  slug: CategorySlug;
  label: string;
  singular: string;
  plural: string;
  description: string;
}

export const CATEGORIES: Category[] = [
  {
    slug: "jogos-de-tabuleiro",
    label: "Jogos de Tabuleiro",
    singular: "jogo",
    plural: "jogos",
    description: "Jogos completos, com peças conferidas antes de anunciar.",
  },
  {
    slug: "roupas",
    label: "Roupas",
    singular: "peça",
    plural: "peças",
    description: "Peças em bom estado, lavadas e prontas para usar.",
  },
  {
    slug: "moveis",
    label: "Móveis",
    singular: "móvel",
    plural: "móveis",
    description: "Retirada combinada por causa do tamanho e do peso.",
  },
  {
    slug: "sapatos",
    label: "Sapatos",
    singular: "par",
    plural: "pares",
    description: "Numeração e estado de uso descritos em cada anúncio.",
  },
  {
    slug: "discos",
    label: "Discos",
    singular: "disco",
    plural: "discos",
    description: "Vinis de uma coleção pessoal, guardados com carinho.",
  },
  {
    slug: "objetos-gerais",
    label: "Objetos Gerais",
    singular: "objeto",
    plural: "objetos",
    description: "Itens variados de casa e uso pessoal.",
  },
  {
    slug: "cozinha",
    label: "Cozinha",
    singular: "item",
    plural: "itens",
    description: "Utensílios e equipamentos de cozinha em bom estado.",
  },
  {
    slug: "livros",
    label: "Livros",
    singular: "livro",
    plural: "livros",
    description: "Livros lidos e prontos para ganhar um novo dono.",
  },
  {
    slug: "eletronicos",
    label: "Eletrônicos",
    singular: "aparelho",
    plural: "aparelhos",
    description: "Eletrônicos testados e funcionando antes de anunciar.",
  },
];

export function getCategory(slug: CategorySlug): Category {
  const category = CATEGORIES.find((c) => c.slug === slug);
  if (!category) throw new Error(`Categoria desconhecida: ${slug}`);
  return category;
}

export type SellerId = "mateus" | "bella";

export interface SellerInfo {
  id: SellerId;
  name: string;
  whatsapp: string;
}

export const SELLERS: Record<SellerId, SellerInfo> = {
  mateus: { id: "mateus", name: "Mateus", whatsapp: "5511985073670" },
  bella: { id: "bella", name: "Bella", whatsapp: "5511987710543" },
};

export type Condition =
  | "Lacrado"
  | "Bem conservado"
  | "Com marcas de uso"
  | "Com defeitos ou problemas";

export interface Photo {
  src: string;
  alt: string;
}

export interface Listing {
  id: string;
  title: string;
  category: CategorySlug;
  price?: number;
  condition?: Condition;
  year?: number;
  languages?: string[];
  brand?: string;
  color?: string;
  size?: string;
  author?: string;
  tags?: string[];
  description: string;
  photos: Photo[];
  seller: SellerId;
  sold: boolean;
}

export const LISTINGS: Listing[] = [
  {
    id: "sky-team",
    title: "Sky Team",
    category: "jogos-de-tabuleiro",
    price: 170,
    condition: "Bem conservado",
    languages: ["🇧🇷 Português"],
    description:
      "Jogo cooperativo para dois jogadores, poucas partidas jogadas. Caixa e componentes em ótimo estado.",
    photos: [
      { src: "/images/jogos-de-tabuleiro/sky-team/01.webp", alt: "Sky Team - foto 1" },
      { src: "/images/jogos-de-tabuleiro/sky-team/02.webp", alt: "Sky Team - foto 2" },
      { src: "/images/jogos-de-tabuleiro/sky-team/03.webp", alt: "Sky Team - foto 3" },
      { src: "/images/jogos-de-tabuleiro/sky-team/04.webp", alt: "Sky Team - foto 4" },
      { src: "/images/jogos-de-tabuleiro/sky-team/05.webp", alt: "Sky Team - foto 5" },
      { src: "/images/jogos-de-tabuleiro/sky-team/06.webp", alt: "Sky Team - foto 6" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "cores-com-dicas",
    title: "Cores com Dicas",
    category: "jogos-de-tabuleiro",
    price: 130,
    condition: "Com defeitos ou problemas",
    languages: ["🇧🇷 Português"],
    description:
      "Algumas cartas com problemas de desgaste (jogadas sem sleeves). Tabuleiro e demais componentes completos.",
    photos: [
      { src: "/images/jogos-de-tabuleiro/cores-com-dicas/01.webp", alt: "Cores com Dicas - foto 1" },
      { src: "/images/jogos-de-tabuleiro/cores-com-dicas/02.webp", alt: "Cores com Dicas - foto 2" },
      { src: "/images/jogos-de-tabuleiro/cores-com-dicas/03.webp", alt: "Cores com Dicas - foto 3" },
      { src: "/images/jogos-de-tabuleiro/cores-com-dicas/04.webp", alt: "Cores com Dicas - foto 4" },
      { src: "/images/jogos-de-tabuleiro/cores-com-dicas/05.webp", alt: "Cores com Dicas - foto 5" },
      { src: "/images/jogos-de-tabuleiro/cores-com-dicas/06.webp", alt: "Cores com Dicas - foto 6" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "heat-pedal-to-the-metal",
    title: "Heat: Pedal to the Metal + Expansão Chuva Forte",
    category: "jogos-de-tabuleiro",
    price: 530,
    condition: "Bem conservado",
    languages: ["🇧🇷 Português"],
    description:
      "Jogo base com a expansão Chuva Forte incluída. Cartas protegidas com sleeves desde a primeira partida.",
    photos: [
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/01.webp", alt: "Heat: Pedal to the Metal - foto 1" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/02.webp", alt: "Heat: Pedal to the Metal - foto 2" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/03.webp", alt: "Heat: Pedal to the Metal - foto 3" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/04.webp", alt: "Heat: Pedal to the Metal - foto 4" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/05.webp", alt: "Heat: Pedal to the Metal - foto 5" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/06.webp", alt: "Heat: Pedal to the Metal - foto 6" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/07.webp", alt: "Heat: Pedal to the Metal - foto 7" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/08.webp", alt: "Heat: Pedal to the Metal - foto 8" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/09.webp", alt: "Heat: Pedal to the Metal - foto 9" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/10.webp", alt: "Heat: Pedal to the Metal - foto 10" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/11.webp", alt: "Heat: Pedal to the Metal - foto 11" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/12.webp", alt: "Heat: Pedal to the Metal - foto 12" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/13.webp", alt: "Heat: Pedal to the Metal - foto 13" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/14.webp", alt: "Heat: Pedal to the Metal - foto 14" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/15.webp", alt: "Heat: Pedal to the Metal - foto 15" },
      { src: "/images/jogos-de-tabuleiro/heat-pedal-to-the-metal/16.webp", alt: "Heat: Pedal to the Metal - foto 16" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "robinson-crusoe",
    title: "Robinson Crusoe: Aventuras na Ilha Amaldiçoada",
    category: "jogos-de-tabuleiro",
    price: 250,
    condition: "Com marcas de uso",
    languages: ["🇧🇷 Português"],
    description:
      "Cartas protegidas com sleeves. Componentes completos, com marcas de uso normais de várias partidas.",
    photos: [
      { src: "/images/jogos-de-tabuleiro/robinson-crusoe/01.webp", alt: "Robinson Crusoe - foto 1" },
      { src: "/images/jogos-de-tabuleiro/robinson-crusoe/02.webp", alt: "Robinson Crusoe - foto 2" },
      { src: "/images/jogos-de-tabuleiro/robinson-crusoe/03.webp", alt: "Robinson Crusoe - foto 3" },
      { src: "/images/jogos-de-tabuleiro/robinson-crusoe/04.webp", alt: "Robinson Crusoe - foto 4" },
      { src: "/images/jogos-de-tabuleiro/robinson-crusoe/05.webp", alt: "Robinson Crusoe - foto 5" },
      { src: "/images/jogos-de-tabuleiro/robinson-crusoe/06.webp", alt: "Robinson Crusoe - foto 6" },
      { src: "/images/jogos-de-tabuleiro/robinson-crusoe/07.webp", alt: "Robinson Crusoe - foto 7" },
      { src: "/images/jogos-de-tabuleiro/robinson-crusoe/08.webp", alt: "Robinson Crusoe - foto 8" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "daybreak",
    title: "Daybreak",
    category: "jogos-de-tabuleiro",
    price: 330,
    condition: "Bem conservado",
    languages: ["🇧🇷 Português"],
    description:
      "Cartas protegidas com sleeves desde a primeira partida. Componentes completos e bem cuidados.",
    photos: [
      { src: "/images/jogos-de-tabuleiro/daybreak/01.webp", alt: "Daybreak - foto 1" },
      { src: "/images/jogos-de-tabuleiro/daybreak/02.webp", alt: "Daybreak - foto 2" },
      { src: "/images/jogos-de-tabuleiro/daybreak/03.webp", alt: "Daybreak - foto 3" },
      { src: "/images/jogos-de-tabuleiro/daybreak/04.webp", alt: "Daybreak - foto 4" },
      { src: "/images/jogos-de-tabuleiro/daybreak/05.webp", alt: "Daybreak - foto 5" },
      { src: "/images/jogos-de-tabuleiro/daybreak/06.webp", alt: "Daybreak - foto 6" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "harmonies",
    title: "Harmonies",
    category: "jogos-de-tabuleiro",
    price: 170,
    condition: "Bem conservado",
    languages: ["🇧🇷 Português"],
    description:
      "Cartas protegidas com sleeves. Jogo em ótimo estado, poucas partidas jogadas.",
    photos: [
      { src: "/images/jogos-de-tabuleiro/harmonies/01.webp", alt: "Harmonies - foto 1" },
      { src: "/images/jogos-de-tabuleiro/harmonies/02.webp", alt: "Harmonies - foto 2" },
      { src: "/images/jogos-de-tabuleiro/harmonies/03.webp", alt: "Harmonies - foto 3" },
      { src: "/images/jogos-de-tabuleiro/harmonies/04.webp", alt: "Harmonies - foto 4" },
      { src: "/images/jogos-de-tabuleiro/harmonies/05.webp", alt: "Harmonies - foto 5" },
      { src: "/images/jogos-de-tabuleiro/harmonies/06.webp", alt: "Harmonies - foto 6" },
      { src: "/images/jogos-de-tabuleiro/harmonies/07.webp", alt: "Harmonies - foto 7" },
      { src: "/images/jogos-de-tabuleiro/harmonies/08.webp", alt: "Harmonies - foto 8" },
      { src: "/images/jogos-de-tabuleiro/harmonies/09.webp", alt: "Harmonies - foto 9" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "spirit-island",
    title: "Spirit Island",
    category: "jogos-de-tabuleiro",
    price: 330,
    condition: "Bem conservado",
    languages: ["🇺🇸 Inglês"],
    description:
      "Edição em inglês (Fabled Nexus). Cartas protegidas com sleeves desde a primeira partida.",
    photos: [
      { src: "/images/jogos-de-tabuleiro/spirit-island/01.webp", alt: "Spirit Island - foto 1" },
      { src: "/images/jogos-de-tabuleiro/spirit-island/02.webp", alt: "Spirit Island - foto 2" },
      { src: "/images/jogos-de-tabuleiro/spirit-island/03.webp", alt: "Spirit Island - foto 3" },
      { src: "/images/jogos-de-tabuleiro/spirit-island/04.webp", alt: "Spirit Island - foto 4" },
      { src: "/images/jogos-de-tabuleiro/spirit-island/05.webp", alt: "Spirit Island - foto 5" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "blazer-grafite-48r",
    title: "Blazer",
    category: "roupas",
    color: "Grafite",
    size: "48R",
    description: "Blazer, grafite, tamanho 48R.",
    photos: [
      { src: "/images/roupas/blazer-grafite-48r/01.webp", alt: "Blazer - foto 1" },
      { src: "/images/roupas/blazer-grafite-48r/02.webp", alt: "Blazer - foto 2" },
      { src: "/images/roupas/blazer-grafite-48r/03.webp", alt: "Blazer - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "blazer-pentel-gelo-tamanho-50",
    title: "Blazer",
    category: "roupas",
    brand: "Pentel",
    color: "Gelo",
    size: "50",
    description: "Blazer da Pentel, gelo, tamanho 50.",
    photos: [
      { src: "/images/roupas/blazer-pentel-gelo-tamanho-50/01.webp", alt: "Blazer - foto 1" },
      { src: "/images/roupas/blazer-pentel-gelo-tamanho-50/02.webp", alt: "Blazer - foto 2" },
      { src: "/images/roupas/blazer-pentel-gelo-tamanho-50/03.webp", alt: "Blazer - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "blusa-fleece-decathlon-preto-g",
    title: "Blusa Fleece",
    category: "roupas",
    brand: "Decathlon",
    color: "Preto",
    size: "G",
    description: "Blusa Fleece da Decathlon, preto, tamanho G.",
    photos: [
      { src: "/images/roupas/blusa-fleece-decathlon-preto-g/01.webp", alt: "Blusa Fleece - foto 1" },
      { src: "/images/roupas/blusa-fleece-decathlon-preto-g/02.webp", alt: "Blusa Fleece - foto 2" },
      { src: "/images/roupas/blusa-fleece-decathlon-preto-g/03.webp", alt: "Blusa Fleece - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "camisa-manga-curta-artesanal-sem-marca-branca-com-detalhes-em-vermelho-e-azul-g",
    title: "Camisa Manga Curta",
    category: "roupas",
    brand: "Artesanal-Sem Marca",
    color: "Branca com detalhes em vermelho e azul",
    size: "G",
    description: "Camisa Manga Curta da Artesanal-Sem Marca, branca com detalhes em vermelho e azul, tamanho G.",
    photos: [
      { src: "/images/roupas/camisa-manga-curta-artesanal-sem-marca-branca-com-detalhes-em-vermelho-e-azul-g/01.webp", alt: "Camisa Manga Curta - foto 1" },
      { src: "/images/roupas/camisa-manga-curta-artesanal-sem-marca-branca-com-detalhes-em-vermelho-e-azul-g/02.webp", alt: "Camisa Manga Curta - foto 2" },
      { src: "/images/roupas/camisa-manga-curta-artesanal-sem-marca-branca-com-detalhes-em-vermelho-e-azul-g/03.webp", alt: "Camisa Manga Curta - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "camisa-manga-curta-central-beach-g",
    title: "Camisa Manga Curta",
    category: "roupas",
    brand: "Central Beach",
    size: "G",
    description: "Camisa Manga Curta da Central Beach, tamanho G.",
    photos: [
      { src: "/images/roupas/camisa-manga-curta-central-beach-g/01.webp", alt: "Camisa Manga Curta - foto 1" },
      { src: "/images/roupas/camisa-manga-curta-central-beach-g/02.webp", alt: "Camisa Manga Curta - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "camisa-manga-curta-hering-verde-com-detalhes-em-branco-g",
    title: "Camisa Manga Curta",
    category: "roupas",
    brand: "Hering",
    color: "Verde com detalhes em branco",
    size: "G",
    description: "Camisa Manga Curta da Hering, verde com detalhes em branco, tamanho G.",
    photos: [
      { src: "/images/roupas/camisa-manga-curta-hering-verde-com-detalhes-em-branco-g/01.webp", alt: "Camisa Manga Curta - foto 1" },
      { src: "/images/roupas/camisa-manga-curta-hering-verde-com-detalhes-em-branco-g/02.webp", alt: "Camisa Manga Curta - foto 2" },
      { src: "/images/roupas/camisa-manga-curta-hering-verde-com-detalhes-em-branco-g/03.webp", alt: "Camisa Manga Curta - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "camisa-manga-curta-h-m-branca-com-detalhes-em-preto-m",
    title: "Camisa Manga Curta",
    category: "roupas",
    brand: "H&M",
    color: "Branca com detalhes em preto",
    size: "M",
    description: "Camisa Manga Curta da H&M, branca com detalhes em preto, tamanho M.",
    photos: [
      { src: "/images/roupas/camisa-manga-curta-h-m-branca-com-detalhes-em-preto-m/01.webp", alt: "Camisa Manga Curta - foto 1" },
      { src: "/images/roupas/camisa-manga-curta-h-m-branca-com-detalhes-em-preto-m/02.webp", alt: "Camisa Manga Curta - foto 2" },
      { src: "/images/roupas/camisa-manga-curta-h-m-branca-com-detalhes-em-preto-m/03.webp", alt: "Camisa Manga Curta - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "camisa-manga-curta-pool-azul-g",
    title: "Camisa Manga Curta",
    category: "roupas",
    brand: "Pool",
    color: "Azul",
    size: "G",
    description: "Camisa Manga Curta da Pool, azul, tamanho G.",
    photos: [
      { src: "/images/roupas/camisa-manga-curta-pool-azul-g/01.webp", alt: "Camisa Manga Curta - foto 1" },
      { src: "/images/roupas/camisa-manga-curta-pool-azul-g/02.webp", alt: "Camisa Manga Curta - foto 2" },
      { src: "/images/roupas/camisa-manga-curta-pool-azul-g/03.webp", alt: "Camisa Manga Curta - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "camisa-manga-longa-marfino-azul-escuro-gg",
    title: "Camisa Manga Longa",
    category: "roupas",
    brand: "Marfino",
    color: "Azul escuro",
    size: "GG",
    description: "Camisa Manga Longa da Marfino, azul escuro, tamanho GG.",
    photos: [
      { src: "/images/roupas/camisa-manga-longa-marfino-azul-escuro-gg/01.webp", alt: "Camisa Manga Longa - foto 1" },
      { src: "/images/roupas/camisa-manga-longa-marfino-azul-escuro-gg/02.webp", alt: "Camisa Manga Longa - foto 2" },
      { src: "/images/roupas/camisa-manga-longa-marfino-azul-escuro-gg/03.webp", alt: "Camisa Manga Longa - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "camisa-manga-longa-xadrez-blue-steel-c-a-azul-e-preta-g",
    title: "Camisa Manga Longa Xadrez",
    category: "roupas",
    brand: "Blue Steel(C&A)",
    color: "Azul e preta",
    size: "G",
    description: "Camisa Manga Longa Xadrez da Blue Steel(C&A), azul e preta, tamanho G.",
    photos: [
      { src: "/images/roupas/camisa-manga-longa-xadrez-blue-steel-c-a-azul-e-preta-g/01.webp", alt: "Camisa Manga Longa Xadrez - foto 1" },
      { src: "/images/roupas/camisa-manga-longa-xadrez-blue-steel-c-a-azul-e-preta-g/02.webp", alt: "Camisa Manga Longa Xadrez - foto 2" },
      { src: "/images/roupas/camisa-manga-longa-xadrez-blue-steel-c-a-azul-e-preta-g/03.webp", alt: "Camisa Manga Longa Xadrez - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "camisa-social-preta-renner-tamanho-2",
    title: "Camisa Social Preta",
    category: "roupas",
    brand: "Renner",
    size: "2",
    description: "Camisa Social Preta da Renner, tamanho 2.",
    photos: [
      { src: "/images/roupas/camisa-social-preta-renner-tamanho-2/01.webp", alt: "Camisa Social Preta - foto 1" },
      { src: "/images/roupas/camisa-social-preta-renner-tamanho-2/02.webp", alt: "Camisa Social Preta - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "camisa-xadrez-hering-azul-e-vermelha-g",
    title: "Camisa Xadrez",
    category: "roupas",
    brand: "Hering",
    color: "Azul e vermelha",
    size: "G",
    description: "Camisa Xadrez da Hering, azul e vermelha, tamanho G.",
    photos: [
      { src: "/images/roupas/camisa-xadrez-hering-azul-e-vermelha-g/01.webp", alt: "Camisa Xadrez - foto 1" },
      { src: "/images/roupas/camisa-xadrez-hering-azul-e-vermelha-g/02.webp", alt: "Camisa Xadrez - foto 2" },
      { src: "/images/roupas/camisa-xadrez-hering-azul-e-vermelha-g/03.webp", alt: "Camisa Xadrez - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "colete-pentel-preto-m",
    title: "Colete",
    category: "roupas",
    brand: "Pentel",
    color: "Preto",
    size: "M",
    description: "Colete da Pentel, preto, tamanho M.",
    photos: [
      { src: "/images/roupas/colete-pentel-preto-m/01.webp", alt: "Colete - foto 1" },
      { src: "/images/roupas/colete-pentel-preto-m/02.webp", alt: "Colete - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "jaqueta-budweiser-ambev-vermelho-m",
    title: "Jaqueta",
    category: "roupas",
    brand: "Budweiser(Ambev)",
    color: "Vermelho",
    size: "M",
    description: "Jaqueta da Budweiser(Ambev), vermelho, tamanho M.",
    photos: [
      { src: "/images/roupas/jaqueta-budweiser-ambev-vermelho-m/01.webp", alt: "Jaqueta - foto 1" },
      { src: "/images/roupas/jaqueta-budweiser-ambev-vermelho-m/02.webp", alt: "Jaqueta - foto 2" },
      { src: "/images/roupas/jaqueta-budweiser-ambev-vermelho-m/03.webp", alt: "Jaqueta - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "jaqueta-c-a-marrom-m",
    title: "Jaqueta",
    category: "roupas",
    brand: "C&A",
    color: "Marrom",
    size: "M",
    description: "Jaqueta da C&A, marrom, tamanho M.",
    photos: [
      { src: "/images/roupas/jaqueta-c-a-marrom-m/01.webp", alt: "Jaqueta - foto 1" },
      { src: "/images/roupas/jaqueta-c-a-marrom-m/02.webp", alt: "Jaqueta - foto 2" },
      { src: "/images/roupas/jaqueta-c-a-marrom-m/03.webp", alt: "Jaqueta - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "jaqueta-impermeavel-beats-ambev-azul-e-rosa-g",
    title: "Jaqueta Impermeável",
    category: "roupas",
    brand: "Beats(Ambev)",
    color: "Azul e rosa",
    size: "G",
    description: "Jaqueta Impermeável da Beats(Ambev), azul e rosa, tamanho G.",
    photos: [
      { src: "/images/roupas/jaqueta-impermeavel-beats-ambev-azul-e-rosa-g/01.webp", alt: "Jaqueta Impermeável - foto 1" },
      { src: "/images/roupas/jaqueta-impermeavel-beats-ambev-azul-e-rosa-g/02.webp", alt: "Jaqueta Impermeável - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "jaqueta-impermeavel-decathlon-azul-g",
    title: "Jaqueta Impermeável",
    category: "roupas",
    brand: "Decathlon",
    color: "Azul",
    size: "G",
    description: "Jaqueta Impermeável da Decathlon, azul, tamanho G.",
    photos: [
      { src: "/images/roupas/jaqueta-impermeavel-decathlon-azul-g/01.webp", alt: "Jaqueta Impermeável - foto 1" },
      { src: "/images/roupas/jaqueta-impermeavel-decathlon-azul-g/02.webp", alt: "Jaqueta Impermeável - foto 2" },
      { src: "/images/roupas/jaqueta-impermeavel-decathlon-azul-g/03.webp", alt: "Jaqueta Impermeável - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "jaqueta-moletom-gap-preto-m",
    title: "Jaqueta Moletom",
    category: "roupas",
    brand: "GAP",
    color: "Preto",
    size: "M",
    description: "Jaqueta Moletom da GAP, preto, tamanho M.",
    photos: [
      { src: "/images/roupas/jaqueta-moletom-gap-preto-m/01.webp", alt: "Jaqueta Moletom - foto 1" },
      { src: "/images/roupas/jaqueta-moletom-gap-preto-m/02.webp", alt: "Jaqueta Moletom - foto 2" },
      { src: "/images/roupas/jaqueta-moletom-gap-preto-m/03.webp", alt: "Jaqueta Moletom - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "jaqueta-primaverasounds-2022-pull-bear-branca-com-detalhes-em-azul-m",
    title: "Jaqueta Primavera Sounds 2022",
    category: "roupas",
    brand: "Pull&Bear",
    color: "Branca com detalhes em azul",
    size: "M",
    description: "Jaqueta Primavera Sounds 2022 da Pull&Bear, branca com detalhes em azul, tamanho M.",
    photos: [
      { src: "/images/roupas/jaqueta-primaverasounds-2022-pull-bear-branca-com-detalhes-em-azul-m/01.webp", alt: "Jaqueta Primavera Sounds 2022 - foto 1" },
      { src: "/images/roupas/jaqueta-primaverasounds-2022-pull-bear-branca-com-detalhes-em-azul-m/02.webp", alt: "Jaqueta Primavera Sounds 2022 - foto 2" },
      { src: "/images/roupas/jaqueta-primaverasounds-2022-pull-bear-branca-com-detalhes-em-azul-m/03.webp", alt: "Jaqueta Primavera Sounds 2022 - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "jaqueta-thrasher-bordo-vinho-m",
    title: "Jaqueta",
    category: "roupas",
    brand: "Thrasher",
    color: "Bordô-Vinho",
    size: "M",
    description: "Jaqueta da Thrasher, bordô-vinho, tamanho M.",
    photos: [
      { src: "/images/roupas/jaqueta-thrasher-bordo-vinho-m/01.webp", alt: "Jaqueta - foto 1" },
      { src: "/images/roupas/jaqueta-thrasher-bordo-vinho-m/02.webp", alt: "Jaqueta - foto 2" },
      { src: "/images/roupas/jaqueta-thrasher-bordo-vinho-m/03.webp", alt: "Jaqueta - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "jaqueta-uruguay-sem-marca-azul-escuro-g",
    title: "Jaqueta Uruguay",
    category: "roupas",
    color: "Azul escuro",
    size: "G",
    description: "Jaqueta Uruguay, azul escuro, tamanho G.",
    photos: [
      { src: "/images/roupas/jaqueta-uruguay-sem-marca-azul-escuro-g/01.webp", alt: "Jaqueta Uruguay - foto 1" },
      { src: "/images/roupas/jaqueta-uruguay-sem-marca-azul-escuro-g/02.webp", alt: "Jaqueta Uruguay - foto 2" },
      { src: "/images/roupas/jaqueta-uruguay-sem-marca-azul-escuro-g/03.webp", alt: "Jaqueta Uruguay - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "moletom-canguru-amsterdam-sem-marca-vermelho-g",
    title: "Moletom Canguru Amsterdam",
    category: "roupas",
    color: "Vermelho",
    size: "G",
    description: "Moletom Canguru Amsterdam, vermelho, tamanho G.",
    photos: [
      { src: "/images/roupas/moletom-canguru-amsterdam-sem-marca-vermelho-g/01.webp", alt: "Moletom Canguru Amsterdam - foto 1" },
      { src: "/images/roupas/moletom-canguru-amsterdam-sem-marca-vermelho-g/02.webp", alt: "Moletom Canguru Amsterdam - foto 2" },
      { src: "/images/roupas/moletom-canguru-amsterdam-sem-marca-vermelho-g/03.webp", alt: "Moletom Canguru Amsterdam - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "moletom-twitter-pal-frente-known-issue-preto-com-detalhes-em-branco-g",
    title: "Moletom Twitter PAL Frente",
    category: "roupas",
    brand: "Known Issue",
    color: "Preto com detalhes em branco",
    size: "G",
    description: "Moletom Twitter PAL Frente da Known Issue, preto com detalhes em branco, tamanho G.",
    photos: [
      { src: "/images/roupas/moletom-twitter-pal-frente-known-issue-preto-com-detalhes-em-branco-g/01.webp", alt: "Moletom Twitter PAL Frente - foto 1" },
      { src: "/images/roupas/moletom-twitter-pal-frente-known-issue-preto-com-detalhes-em-branco-g/02.webp", alt: "Moletom Twitter PAL Frente - foto 2" },
      { src: "/images/roupas/moletom-twitter-pal-frente-known-issue-preto-com-detalhes-em-branco-g/03.webp", alt: "Moletom Twitter PAL Frente - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "moletom-twitter-redbird-champion-vermelho-xg",
    title: "Moletom Twitter Redbird",
    category: "roupas",
    brand: "Champion",
    color: "Vermelho",
    size: "XG",
    description: "Moletom Twitter Redbird da Champion, vermelho, tamanho XG.",
    photos: [
      { src: "/images/roupas/moletom-twitter-redbird-champion-vermelho-xg/01.webp", alt: "Moletom Twitter Redbird - foto 1" },
      { src: "/images/roupas/moletom-twitter-redbird-champion-vermelho-xg/02.webp", alt: "Moletom Twitter Redbird - foto 2" },
      { src: "/images/roupas/moletom-twitter-redbird-champion-vermelho-xg/03.webp", alt: "Moletom Twitter Redbird - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "sueter-budweiser-ambev-vermelho-m",
    title: "Suéter",
    category: "roupas",
    brand: "Budweiser(Ambev)",
    color: "Vermelho",
    size: "M",
    description: "Suéter da Budweiser(Ambev), vermelho, tamanho M.",
    photos: [
      { src: "/images/roupas/sueter-budweiser-ambev-vermelho-m/01.webp", alt: "Suéter - foto 1" },
      { src: "/images/roupas/sueter-budweiser-ambev-vermelho-m/02.webp", alt: "Suéter - foto 2" },
      { src: "/images/roupas/sueter-budweiser-ambev-vermelho-m/03.webp", alt: "Suéter - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "blazer-h-m-branco-com-listras-em-preto-size-tbd",
    title: "Blazer",
    category: "roupas",
    brand: "H&M",
    color: "Branco com listras em preto",
    description: "Blazer da H&M, branco com listras em preto, tamanho a definir.",
    photos: [
      { src: "/images/roupas/blazer-h-m-branco-com-listras-em-preto-size-tbd/01.webp", alt: "Blazer - foto 1" },
      { src: "/images/roupas/blazer-h-m-branco-com-listras-em-preto-size-tbd/02.webp", alt: "Blazer - foto 2" },
      { src: "/images/roupas/blazer-h-m-branco-com-listras-em-preto-size-tbd/03.webp", alt: "Blazer - foto 3" },
    ],
    seller: "bella",
    sold: false,
  },
  {
    id: "blusa-colete-h-m-branca-com-detalhes-coloridos-tbd",
    title: "Blusa Colete",
    category: "roupas",
    brand: "H&M",
    color: "Branca com detalhes coloridos",
    description: "Blusa Colete da H&M, branca com detalhes coloridos, tamanho a definir.",
    photos: [
      { src: "/images/roupas/blusa-colete-h-m-branca-com-detalhes-coloridos-tbd/01.webp", alt: "Blusa Colete - foto 1" },
      { src: "/images/roupas/blusa-colete-h-m-branca-com-detalhes-coloridos-tbd/02.webp", alt: "Blusa Colete - foto 2" },
      { src: "/images/roupas/blusa-colete-h-m-branca-com-detalhes-coloridos-tbd/03.webp", alt: "Blusa Colete - foto 3" },
    ],
    seller: "bella",
    sold: false,
  },
  {
    id: "camisa-manga-curta-cropped-dzarm-laranja-g",
    title: "Camisa Manga Curta Cropped",
    category: "roupas",
    brand: "DZARM",
    color: "Laranja",
    size: "G",
    description: "Camisa Manga Curta Cropped da DZARM, laranja, tamanho G.",
    photos: [
      { src: "/images/roupas/camisa-manga-curta-cropped-dzarm-laranja-g/01.webp", alt: "Camisa Manga Curta Cropped - foto 1" },
      { src: "/images/roupas/camisa-manga-curta-cropped-dzarm-laranja-g/02.webp", alt: "Camisa Manga Curta Cropped - foto 2" },
    ],
    seller: "bella",
    sold: false,
  },
  {
    id: "camisa-manga-longa-mango-grafite-m",
    title: "Camisa Manga Longa",
    category: "roupas",
    brand: "Mango",
    color: "Grafite",
    size: "M",
    description: "Camisa Manga Longa da Mango, grafite, tamanho M.",
    photos: [
      { src: "/images/roupas/camisa-manga-longa-mango-grafite-m/01.webp", alt: "Camisa Manga Longa - foto 1" },
      { src: "/images/roupas/camisa-manga-longa-mango-grafite-m/02.webp", alt: "Camisa Manga Longa - foto 2" },
      { src: "/images/roupas/camisa-manga-longa-mango-grafite-m/03.webp", alt: "Camisa Manga Longa - foto 3" },
    ],
    seller: "bella",
    sold: false,
  },
  {
    id: "jaqueta-hering-branca-m",
    title: "Jaqueta",
    category: "roupas",
    brand: "Hering",
    color: "Branca",
    size: "M",
    description: "Jaqueta da Hering, branca, tamanho M.",
    photos: [
      { src: "/images/roupas/jaqueta-hering-branca-m/01.webp", alt: "Jaqueta - foto 1" },
      { src: "/images/roupas/jaqueta-hering-branca-m/02.webp", alt: "Jaqueta - foto 2" },
      { src: "/images/roupas/jaqueta-hering-branca-m/03.webp", alt: "Jaqueta - foto 3" },
      { src: "/images/roupas/jaqueta-hering-branca-m/04.webp", alt: "Jaqueta - foto 4" },
    ],
    seller: "bella",
    sold: false,
  },
  {
    id: "vestido-amaro-preto-gg",
    title: "Vestido",
    category: "roupas",
    brand: "Amaro",
    color: "Preto",
    size: "GG",
    description: "Vestido da Amaro, preto, tamanho GG.",
    photos: [
      { src: "/images/roupas/vestido-amaro-preto-gg/01.webp", alt: "Vestido - foto 1" },
      { src: "/images/roupas/vestido-amaro-preto-gg/02.webp", alt: "Vestido - foto 2" },
      { src: "/images/roupas/vestido-amaro-preto-gg/03.webp", alt: "Vestido - foto 3" },
    ],
    seller: "bella",
    sold: false,
  },
  {
    id: "vestido-bluesteel-branco-e-vermelho-gg",
    title: "Vestido",
    category: "roupas",
    brand: "Bluesteel",
    color: "Branco e vermelho",
    size: "GG",
    description: "Vestido da Bluesteel, branco e vermelho, tamanho GG.",
    photos: [
      { src: "/images/roupas/vestido-bluesteel-branco-e-vermelho-gg/01.webp", alt: "Vestido - foto 1" },
      { src: "/images/roupas/vestido-bluesteel-branco-e-vermelho-gg/02.webp", alt: "Vestido - foto 2" },
      { src: "/images/roupas/vestido-bluesteel-branco-e-vermelho-gg/03.webp", alt: "Vestido - foto 3" },
    ],
    seller: "bella",
    sold: false,
  },
  {
    id: "vestido-transpassado-hering-branco-e-preto-g",
    title: "Vestido Transpassado",
    category: "roupas",
    brand: "Hering",
    color: "Branco e preto",
    size: "G",
    description: "Vestido Transpassado da Hering, branco e preto, tamanho G.",
    photos: [
      { src: "/images/roupas/vestido-transpassado-hering-branco-e-preto-g/01.webp", alt: "Vestido Transpassado - foto 1" },
      { src: "/images/roupas/vestido-transpassado-hering-branco-e-preto-g/02.webp", alt: "Vestido Transpassado - foto 2" },
      { src: "/images/roupas/vestido-transpassado-hering-branco-e-preto-g/03.webp", alt: "Vestido Transpassado - foto 3" },
    ],
    seller: "bella",
    sold: false,
  },
  {
    id: "mesa-centro",
    title: "Mesa de centro de madeira",
    category: "moveis",
    price: 250,
    condition: "Com marcas de uso",
    description:
      "Mesa de centro maciça, 90x50cm. Alguns riscos de uso normal. Retirada combinada.",
    photos: [],
    seller: "mateus",
    sold: false,
  },
  {
    id: "estante-livros",
    title: "Estante de livros 5 prateleiras",
    category: "moveis",
    price: 180,
    condition: "Bem conservado",
    description: "Estante branca, firme, ótima para livros ou plantas. Desmonta para transporte.",
    photos: [],
    seller: "bella",
    sold: false,
  },
  {
    id: "bota-democrata-marrom-41",
    title: "Bota",
    category: "sapatos",
    brand: "Democrata",
    color: "Marrom",
    size: "41",
    description: "Bota da Democrata, marrom, tamanho 41.",
    photos: [
      { src: "/images/sapatos/bota-democrata-marrom-41/01.webp", alt: "Bota - foto 1" },
      { src: "/images/sapatos/bota-democrata-marrom-41/02.webp", alt: "Bota - foto 2" },
      { src: "/images/sapatos/bota-democrata-marrom-41/03.webp", alt: "Bota - foto 3" },
      { src: "/images/sapatos/bota-democrata-marrom-41/04.webp", alt: "Bota - foto 4" },
      { src: "/images/sapatos/bota-democrata-marrom-41/05.webp", alt: "Bota - foto 5" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "sapato-democrata-cafe-41",
    title: "Sapato",
    category: "sapatos",
    brand: "Democrata",
    color: "Café",
    size: "41",
    description: "Sapato da Democrata, café, tamanho 41.",
    photos: [
      { src: "/images/sapatos/sapato-democrata-cafe-41/01.webp", alt: "Sapato - foto 1" },
      { src: "/images/sapatos/sapato-democrata-cafe-41/02.webp", alt: "Sapato - foto 2" },
      { src: "/images/sapatos/sapato-democrata-cafe-41/03.webp", alt: "Sapato - foto 3" },
      { src: "/images/sapatos/sapato-democrata-cafe-41/04.webp", alt: "Sapato - foto 4" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "tenis-adidas-busenitz-vermelho-41",
    title: "Tênis Busenitz",
    category: "sapatos",
    brand: "Adidas",
    color: "Vermelho",
    size: "41",
    description: "Tênis Busenitz da Adidas, vermelho, tamanho 41.",
    photos: [
      { src: "/images/sapatos/tenis-adidas-busenitz-vermelho-41/01.webp", alt: "Tenis Busenitz - foto 1" },
      { src: "/images/sapatos/tenis-adidas-busenitz-vermelho-41/02.webp", alt: "Tenis Busenitz - foto 2" },
      { src: "/images/sapatos/tenis-adidas-busenitz-vermelho-41/03.webp", alt: "Tenis Busenitz - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "tenis-cavalera-bordo-vinho-41",
    title: "Tênis",
    category: "sapatos",
    brand: "Cavalera",
    color: "Bordô-Vinho",
    size: "41",
    description: "Tênis da Cavalera, bordô-vinho, tamanho 41.",
    photos: [
      { src: "/images/sapatos/tenis-cavalera-bordo-vinho-41/01.webp", alt: "Tenis - foto 1" },
      { src: "/images/sapatos/tenis-cavalera-bordo-vinho-41/02.webp", alt: "Tenis - foto 2" },
      { src: "/images/sapatos/tenis-cavalera-bordo-vinho-41/03.webp", alt: "Tenis - foto 3" },
      { src: "/images/sapatos/tenis-cavalera-bordo-vinho-41/04.webp", alt: "Tenis - foto 4" },
      { src: "/images/sapatos/tenis-cavalera-bordo-vinho-41/05.webp", alt: "Tenis - foto 5" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "tenis-nike-blazers-77-vermelho-e-branco-41",
    title: "Tênis Blazers 77",
    category: "sapatos",
    brand: "Nike",
    color: "Vermelho e branco",
    size: "41",
    description: "Tênis Blazers 77 da Nike, vermelho e branco, tamanho 41.",
    photos: [
      { src: "/images/sapatos/tenis-nike-blazers-77-vermelho-e-branco-41/01.webp", alt: "Tenis Blazers 77 - foto 1" },
      { src: "/images/sapatos/tenis-nike-blazers-77-vermelho-e-branco-41/02.webp", alt: "Tenis Blazers 77 - foto 2" },
      { src: "/images/sapatos/tenis-nike-blazers-77-vermelho-e-branco-41/03.webp", alt: "Tenis Blazers 77 - foto 3" },
      { src: "/images/sapatos/tenis-nike-blazers-77-vermelho-e-branco-41/04.webp", alt: "Tenis Blazers 77 - foto 4" },
      { src: "/images/sapatos/tenis-nike-blazers-77-vermelho-e-branco-41/05.webp", alt: "Tenis Blazers 77 - foto 5" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "tenis-nike-sb-chron-2-branco-e-roxo-37",
    title: "Tênis SB Chron 2",
    category: "sapatos",
    brand: "Nike",
    color: "Branco e roxo",
    size: "37",
    description: "Tênis SB Chron 2 da Nike, branco e roxo, tamanho 37.",
    photos: [
      { src: "/images/sapatos/tenis-nike-sb-chron-2-branco-e-roxo-37/01.webp", alt: "Tenis SB Chron 2 - foto 1" },
      { src: "/images/sapatos/tenis-nike-sb-chron-2-branco-e-roxo-37/02.webp", alt: "Tenis SB Chron 2 - foto 2" },
      { src: "/images/sapatos/tenis-nike-sb-chron-2-branco-e-roxo-37/03.webp", alt: "Tenis SB Chron 2 - foto 3" },
      { src: "/images/sapatos/tenis-nike-sb-chron-2-branco-e-roxo-37/04.webp", alt: "Tenis SB Chron 2 - foto 4" },
      { src: "/images/sapatos/tenis-nike-sb-chron-2-branco-e-roxo-37/05.webp", alt: "Tenis SB Chron 2 - foto 5" },
    ],
    seller: "bella",
    sold: false,
  },
  {
    id: "tenis-nike-sb-chron-2-branco-e-roxo-41",
    title: "Tênis SB Chron 2",
    category: "sapatos",
    brand: "Nike",
    color: "Branco e roxo",
    size: "41",
    description: "Tênis SB Chron 2 da Nike, branco e roxo, tamanho 41.",
    photos: [
      { src: "/images/sapatos/tenis-nike-sb-chron-2-branco-e-roxo-41/01.webp", alt: "Tenis SB Chron 2 - foto 1" },
      { src: "/images/sapatos/tenis-nike-sb-chron-2-branco-e-roxo-41/02.webp", alt: "Tenis SB Chron 2 - foto 2" },
      { src: "/images/sapatos/tenis-nike-sb-chron-2-branco-e-roxo-41/03.webp", alt: "Tenis SB Chron 2 - foto 3" },
      { src: "/images/sapatos/tenis-nike-sb-chron-2-branco-e-roxo-41/04.webp", alt: "Tenis SB Chron 2 - foto 4" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "tenis-vans-oldskool-preto",
    title: "Tênis Oldskool",
    category: "sapatos",
    brand: "Vans",
    color: "Preto",
    size: "37",
    description: "Tênis Oldskool da Vans, preto, tamanho 37.",
    photos: [
      { src: "/images/sapatos/tenis-vans-oldskool-preto/01.webp", alt: "Tenis Oldskool - foto 1" },
      { src: "/images/sapatos/tenis-vans-oldskool-preto/02.webp", alt: "Tenis Oldskool - foto 2" },
      { src: "/images/sapatos/tenis-vans-oldskool-preto/03.webp", alt: "Tenis Oldskool - foto 3" },
    ],
    seller: "bella",
    sold: false,
  },
  {
    id: "tenis-vans-oldskool-van-gogh-vineyard-azul-e-branco-41",
    title: "Tênis Oldskool VAN GOGH (Vineyard)",
    category: "sapatos",
    brand: "Vans",
    color: "Azul e branco",
    size: "41",
    description: "Tênis Oldskool VAN GOGH (Vineyard) da Vans, azul e branco, tamanho 41.",
    photos: [
      { src: "/images/sapatos/tenis-vans-oldskool-van-gogh-vineyard-azul-e-branco-41/01.webp", alt: "Tenis Oldskool VAN GOGH (Vineyard) - foto 1" },
      { src: "/images/sapatos/tenis-vans-oldskool-van-gogh-vineyard-azul-e-branco-41/02.webp", alt: "Tenis Oldskool VAN GOGH (Vineyard) - foto 2" },
      { src: "/images/sapatos/tenis-vans-oldskool-van-gogh-vineyard-azul-e-branco-41/03.webp", alt: "Tenis Oldskool VAN GOGH (Vineyard) - foto 3" },
      { src: "/images/sapatos/tenis-vans-oldskool-van-gogh-vineyard-azul-e-branco-41/04.webp", alt: "Tenis Oldskool VAN GOGH (Vineyard) - foto 4" },
      { src: "/images/sapatos/tenis-vans-oldskool-van-gogh-vineyard-azul-e-branco-41/05.webp", alt: "Tenis Oldskool VAN GOGH (Vineyard) - foto 5" },
      { src: "/images/sapatos/tenis-vans-oldskool-van-gogh-vineyard-azul-e-branco-41/06.webp", alt: "Tenis Oldskool VAN GOGH (Vineyard) - foto 6" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "tenis-vans-sk8hi-branco-e-preto-41",
    title: "Tênis Sk8Hi",
    category: "sapatos",
    brand: "Vans",
    color: "Branco e preto",
    size: "41",
    description: "Tênis Sk8Hi da Vans, branco e preto, tamanho 41.",
    photos: [
      { src: "/images/sapatos/tenis-vans-sk8hi-branco-e-preto-41/01.webp", alt: "Tenis Sk8Hi - foto 1" },
      { src: "/images/sapatos/tenis-vans-sk8hi-branco-e-preto-41/02.webp", alt: "Tenis Sk8Hi - foto 2" },
      { src: "/images/sapatos/tenis-vans-sk8hi-branco-e-preto-41/03.webp", alt: "Tenis Sk8Hi - foto 3" },
      { src: "/images/sapatos/tenis-vans-sk8hi-branco-e-preto-41/04.webp", alt: "Tenis Sk8Hi - foto 4" },
      { src: "/images/sapatos/tenis-vans-sk8hi-branco-e-preto-41/05.webp", alt: "Tenis Sk8Hi - foto 5" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "tenis-vans-sk8hi-yusuke-hanai-vermelho-e-branco-41",
    title: "Tênis Sk8Hi Yusuke Hanai",
    category: "sapatos",
    brand: "Vans",
    color: "Vermelho e branco",
    size: "41",
    description: "Tênis Sk8Hi Yusuke Hanai da Vans, vermelho e branco, tamanho 41.",
    photos: [
      { src: "/images/sapatos/tenis-vans-sk8hi-yusuke-hanai-vermelho-e-branco-41/01.webp", alt: "Tenis Sk8Hi Yusuke Hanai - foto 1" },
      { src: "/images/sapatos/tenis-vans-sk8hi-yusuke-hanai-vermelho-e-branco-41/02.webp", alt: "Tenis Sk8Hi Yusuke Hanai - foto 2" },
      { src: "/images/sapatos/tenis-vans-sk8hi-yusuke-hanai-vermelho-e-branco-41/03.webp", alt: "Tenis Sk8Hi Yusuke Hanai - foto 3" },
      { src: "/images/sapatos/tenis-vans-sk8hi-yusuke-hanai-vermelho-e-branco-41/04.webp", alt: "Tenis Sk8Hi Yusuke Hanai - foto 4" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "american-football",
    title: "American Football LP1",
    category: "discos",
    price: 200,
    condition: "Bem conservado",
    year: 2023,
    description: "Edição de 2023 (Polyvinyl/Balaclava) do álbum de estreia da banda.",
    photos: [
      { src: "/images/discos/american-football/01.webp", alt: "American Football - foto 1" },
      { src: "/images/discos/american-football/02.webp", alt: "American Football - foto 2" },
      { src: "/images/discos/american-football/03.webp", alt: "American Football - foto 3" },
      { src: "/images/discos/american-football/04.webp", alt: "American Football - foto 4" },
      { src: "/images/discos/american-football/05.webp", alt: "American Football - foto 5" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "ana-frango-eletrico",
    title: "Ana Frango Elétrico - Little Electric Chicken Heart",
    category: "discos",
    price: 150,
    condition: "Lacrado",
    year: 2026,
    description: "Vinil lacrado, edição Fábrica Rocinante / Três Selos.",
    photos: [
      {
        src: "/images/discos/ana-frango-eletrico/01.webp",
        alt: "Ana Frango Elétrico - Little Electric Chicken Heart - foto 1",
      },
      {
        src: "/images/discos/ana-frango-eletrico/02.webp",
        alt: "Ana Frango Elétrico - Little Electric Chicken Heart - foto 2",
      },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "criolo-amaro-e-dino",
    title: "Criolo, Amaro e Dino",
    category: "discos",
    price: 100,
    condition: "Lacrado",
    year: 2026,
    description:
      "Edição limitada e numerada do clube de assinantes Três Selos / Fábrica Rocinante. Ainda lacrado.",
    photos: [
      { src: "/images/discos/criolo/01.webp", alt: "Criolo, Amaro e Dino - foto 1" },
      { src: "/images/discos/criolo/02.webp", alt: "Criolo, Amaro e Dino - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "dona-onete",
    title: "Dona Onete - Feitiço Caboclo",
    category: "discos",
    price: 100,
    condition: "Lacrado",
    year: 2026,
    description: "Vinil lacrado, edição do clube de assinantes Três Selos / Fábrica Rocinante.",
    photos: [
      { src: "/images/discos/dona-onete/01.webp", alt: "Dona Onete - Feitiço Caboclo - foto 1" },
      { src: "/images/discos/dona-onete/02.webp", alt: "Dona Onete - Feitiço Caboclo - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "evangelion-finally",
    title: "Evangelion Finally",
    category: "discos",
    price: 120,
    condition: "Lacrado",
    year: 2026,
    description: "Vinil lacrado da trilha sonora de Evangelion.",
    photos: [
      { src: "/images/discos/evangelion/01.webp", alt: "Evangelion Finally - foto 1" },
      { src: "/images/discos/evangelion/02.webp", alt: "Evangelion Finally - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "gabriela-leite",
    title: "Gabriele Leite - Gunûncho",
    category: "discos",
    price: 100,
    condition: "Lacrado",
    year: 2025,
    description: "Vinil lacrado, edição Fábrica Rocinante.",
    photos: [
      { src: "/images/discos/gabriela-leit/01.webp", alt: "Gabriele Leite - Gunûncho - foto 1" },
      { src: "/images/discos/gabriela-leit/02.webp", alt: "Gabriele Leite - Gunûncho - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "house-of-sugar-alex-g",
    title: "Alex G - House of Sugar",
    category: "discos",
    price: 150,
    condition: "Bem conservado",
    year: 2020,
    description: "Edição Domino Recording Co.",
    photos: [
      { src: "/images/discos/house-of-sugar-alex-g/01.webp", alt: "Alex G - House of Sugar - foto 1" },
      { src: "/images/discos/house-of-sugar-alex-g/02.webp", alt: "Alex G - House of Sugar - foto 2" },
      { src: "/images/discos/house-of-sugar-alex-g/03.webp", alt: "Alex G - House of Sugar - foto 3" },
      { src: "/images/discos/house-of-sugar-alex-g/04.webp", alt: "Alex G - House of Sugar - foto 4" },
      { src: "/images/discos/house-of-sugar-alex-g/05.webp", alt: "Alex G - House of Sugar - foto 5" },
      { src: "/images/discos/house-of-sugar-alex-g/06.webp", alt: "Alex G - House of Sugar - foto 6" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "kero-kero-bonito",
    title: "Kero Kero Bonito - Civilisation",
    category: "discos",
    price: 140,
    condition: "Bem conservado",
    year: 2021,
    description: "Com arte gráfica em um alfabeto próprio criado pela banda.",
    photos: [
      { src: "/images/discos/kero-kero-bonito/01.webp", alt: "Kero Kero Bonito - foto 1" },
      { src: "/images/discos/kero-kero-bonito/02.webp", alt: "Kero Kero Bonito - foto 2" },
      { src: "/images/discos/kero-kero-bonito/03.webp", alt: "Kero Kero Bonito - foto 3" },
      { src: "/images/discos/kero-kero-bonito/04.webp", alt: "Kero Kero Bonito - foto 4" },
      { src: "/images/discos/kero-kero-bonito/05.webp", alt: "Kero Kero Bonito - foto 5" },
      { src: "/images/discos/kero-kero-bonito/06.webp", alt: "Kero Kero Bonito - foto 6" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "milton-nascimento-travessia",
    title: "Milton Nascimento - Travessia",
    category: "discos",
    price: 150,
    condition: "Lacrado",
    year: 2026,
    description:
      "Reedição lacrada pelo clube de assinantes Três Selos / Fábrica Rocinante do álbum de estreia de Milton Nascimento.",
    photos: [
      { src: "/images/discos/milton-nascimento/01.webp", alt: "Milton Nascimento - Travessia - foto 1" },
      { src: "/images/discos/milton-nascimento/02.webp", alt: "Milton Nascimento - Travessia - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "aro-de-pilates-liveup-esportes-laranja-r-20",
    title: "Aro de Pilates",
    category: "objetos-gerais",
    price: 20,
    brand: "LiveUp Esportes",
    color: "Laranja",
    description: "Aro de pilates da LiveUp Esportes, laranja.",
    photos: [
      { src: "/images/objetos-gerais/aro-de-pilates-liveup-esportes-laranja-r-20/01.webp", alt: "Aro de Pilates - foto 1" },
      { src: "/images/objetos-gerais/aro-de-pilates-liveup-esportes-laranja-r-20/02.webp", alt: "Aro de Pilates - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "espelho-rei-dos-vidros-44cmx64cm-rs40",
    title: "Espelho",
    category: "objetos-gerais",
    price: 40,
    brand: "Rei dos Vidros",
    size: "44cm x 64cm",
    description: "Espelho da Rei dos Vidros, 44cm x 64cm.",
    photos: [
      { src: "/images/objetos-gerais/espelho-rei-dos-vidros-44cmx64cm-rs40/01.webp", alt: "Espelho - foto 1" },
      { src: "/images/objetos-gerais/espelho-rei-dos-vidros-44cmx64cm-rs40/02.webp", alt: "Espelho - foto 2" },
      { src: "/images/objetos-gerais/espelho-rei-dos-vidros-44cmx64cm-rs40/03.webp", alt: "Espelho - foto 3" },
      { src: "/images/objetos-gerais/espelho-rei-dos-vidros-44cmx64cm-rs40/04.webp", alt: "Espelho - foto 4" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "porta-retrato-westwing-caramelo-r-10",
    title: "Porta-Retrato",
    category: "objetos-gerais",
    price: 10,
    brand: "Westwing",
    color: "Caramelo",
    description: "Porta-retrato da Westwing, caramelo.",
    photos: [
      { src: "/images/objetos-gerais/porta-retrato-westwing-caramelo-r-10/01.webp", alt: "Porta-Retrato - foto 1" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "quadro-moca-com-brinco-de-perola-ikea-r-20",
    title: "Quadro Moça com Brinco de Pérola",
    category: "objetos-gerais",
    price: 20,
    brand: "IKEA",
    description: "Quadro com reprodução de 'Moça com Brinco de Pérola', da IKEA.",
    photos: [
      { src: "/images/objetos-gerais/quadro-moca-com-brinco-de-perola-ikea-r-20/01.webp", alt: "Quadro Moça com Brinco de Pérola - foto 1" },
      { src: "/images/objetos-gerais/quadro-moca-com-brinco-de-perola-ikea-r-20/02.webp", alt: "Quadro Moça com Brinco de Pérola - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "tapete-de-yoga-sem-marca-lilas-r-30",
    title: "Tapete de Yoga",
    category: "objetos-gerais",
    price: 30,
    color: "Lilás",
    description: "Tapete de yoga, lilás.",
    photos: [
      { src: "/images/objetos-gerais/tapete-de-yoga-sem-marca-lilas-r-30/01.webp", alt: "Tapete de Yoga - foto 1" },
      { src: "/images/objetos-gerais/tapete-de-yoga-sem-marca-lilas-r-30/02.webp", alt: "Tapete de Yoga - foto 2" },
      { src: "/images/objetos-gerais/tapete-de-yoga-sem-marca-lilas-r-30/03.webp", alt: "Tapete de Yoga - foto 3" },
      { src: "/images/objetos-gerais/tapete-de-yoga-sem-marca-lilas-r-30/04.webp", alt: "Tapete de Yoga - foto 4" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "cacarola-ferro-fundido-fissler-preta-r-250",
    title: "Caçarola de Ferro Fundido",
    category: "cozinha",
    price: 250,
    brand: "Fissler",
    color: "Preta",
    description: "Caçarola de ferro fundido da Fissler, preta.",
    photos: [
      { src: "/images/cozinha/cacarola-ferro-fundido-fissler-preta-r-250/01.webp", alt: "Caçarola de Ferro Fundido - foto 1" },
      { src: "/images/cozinha/cacarola-ferro-fundido-fissler-preta-r-250/02.webp", alt: "Caçarola de Ferro Fundido - foto 2" },
      { src: "/images/cozinha/cacarola-ferro-fundido-fissler-preta-r-250/03.webp", alt: "Caçarola de Ferro Fundido - foto 3" },
      { src: "/images/cozinha/cacarola-ferro-fundido-fissler-preta-r-250/04.webp", alt: "Caçarola de Ferro Fundido - foto 4" },
      { src: "/images/cozinha/cacarola-ferro-fundido-fissler-preta-r-250/05.webp", alt: "Caçarola de Ferro Fundido - foto 5" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "moedor-de-cafe-grundig-cm3260-preto-r-100",
    title: "Moedor de Café CM3260",
    category: "cozinha",
    price: 100,
    brand: "Grundig",
    color: "Preto",
    description: "Moedor de café da Grundig, modelo CM3260, preto.",
    photos: [
      { src: "/images/cozinha/moedor-de-cafe-grundig-cm3260-preto-r-100/01.webp", alt: "Moedor de Café CM3260 - foto 1" },
      { src: "/images/cozinha/moedor-de-cafe-grundig-cm3260-preto-r-100/02.webp", alt: "Moedor de Café CM3260 - foto 2" },
      { src: "/images/cozinha/moedor-de-cafe-grundig-cm3260-preto-r-100/03.webp", alt: "Moedor de Café CM3260 - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "prensa-francesa-ikea-preto-r-25",
    title: "Prensa Francesa",
    category: "cozinha",
    price: 25,
    brand: "IKEA",
    color: "Preto",
    description: "Prensa francesa da IKEA, preta.",
    photos: [
      { src: "/images/cozinha/prensa-francesa-ikea-preto-r-25/01.webp", alt: "Prensa Francesa - foto 1" },
      { src: "/images/cozinha/prensa-francesa-ikea-preto-r-25/02.webp", alt: "Prensa Francesa - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-a-gente-mira-no-amor-e-acerta-na-solidao-ana-suy-r-20",
    title: "A Gente Mira no Amor e Acerta na Solidão",
    category: "livros",
    price: 20,
    author: "Ana Suy",
    description: "A Gente Mira no Amor e Acerta na Solidão, de Ana Suy.",
    photos: [
      { src: "/images/livros/livro-a-gente-mira-no-amor-e-acerta-na-solidao-ana-suy-r-20/01.webp", alt: "A Gente Mira no Amor e Acerta na Solidão - foto 1" },
      { src: "/images/livros/livro-a-gente-mira-no-amor-e-acerta-na-solidao-ana-suy-r-20/02.webp", alt: "A Gente Mira no Amor e Acerta na Solidão - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-as-pessoas-na-plataforma-5-clare-pooley-r-35",
    title: "As Pessoas na Plataforma 5",
    category: "livros",
    price: 35,
    author: "Clare Pooley",
    description: "As Pessoas na Plataforma 5, de Clare Pooley.",
    photos: [
      { src: "/images/livros/livro-as-pessoas-na-plataforma-5-clare-pooley-r-35/01.webp", alt: "As Pessoas na Plataforma 5 - foto 1" },
      { src: "/images/livros/livro-as-pessoas-na-plataforma-5-clare-pooley-r-35/02.webp", alt: "As Pessoas na Plataforma 5 - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-casa-de-folhas-mark-z-danielezwski-r-140",
    title: "Casa de Folhas",
    category: "livros",
    price: 140,
    author: "Mark Z. Danielewski",
    description: "Casa de Folhas, de Mark Z. Danielewski.",
    photos: [
      { src: "/images/livros/livro-casa-de-folhas-mark-z-danielezwski-r-140/01.webp", alt: "Casa de Folhas - foto 1" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-destrua-esse-diario-keri-smith-r-15",
    title: "Destrua Esse Diário",
    category: "livros",
    price: 15,
    author: "Keri Smith",
    description: "Destrua Esse Diário, de Keri Smith.",
    photos: [
      { src: "/images/livros/livro-destrua-esse-diario-keri-smith-r-15/01.webp", alt: "Destrua Esse Diário - foto 1" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-em-outra-vida-talvez-taylor-jenkins-reid-r-40",
    title: "Em Outra Vida, Talvez?",
    category: "livros",
    price: 40,
    author: "Taylor Jenkins Reid",
    description: "Em Outra Vida, Talvez?, de Taylor Jenkins Reid.",
    photos: [
      { src: "/images/livros/livro-em-outra-vida-talvez-taylor-jenkins-reid-r-40/01.webp", alt: "Em Outra Vida, Talvez? - foto 1" },
      { src: "/images/livros/livro-em-outra-vida-talvez-taylor-jenkins-reid-r-40/02.webp", alt: "Em Outra Vida, Talvez? - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-murdle-volume-1-gt-karber-r-40",
    title: "Murdle Volume 1",
    category: "livros",
    price: 40,
    author: "G.T. Karber",
    description: "Murdle Volume 1, de G.T. Karber.",
    photos: [
      { src: "/images/livros/livro-murdle-volume-1-gt-karber-r-40/01.webp", alt: "Murdle Volume 1 - foto 1" },
      { src: "/images/livros/livro-murdle-volume-1-gt-karber-r-40/02.webp", alt: "Murdle Volume 1 - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-o-livro-de-receitas-do-studio-ghibli-jessica-yun-r-100",
    title: "O Livro de Receitas do Studio Ghibli",
    category: "livros",
    price: 100,
    author: "Jessica Yun",
    description: "O Livro de Receitas do Studio Ghibli, de Jessica Yun.",
    photos: [
      { src: "/images/livros/livro-o-livro-de-receitas-do-studio-ghibli-jessica-yun-r-100/01.webp", alt: "O Livro de Receitas do Studio Ghibli - foto 1" },
      { src: "/images/livros/livro-o-livro-de-receitas-do-studio-ghibli-jessica-yun-r-100/02.webp", alt: "O Livro de Receitas do Studio Ghibli - foto 2" },
      { src: "/images/livros/livro-o-livro-de-receitas-do-studio-ghibli-jessica-yun-r-100/03.webp", alt: "O Livro de Receitas do Studio Ghibli - foto 3" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-o-misterio-dos-principes-na-torre-josephine-tey-r-40",
    title: "O Mistério dos Príncipes na Torre",
    category: "livros",
    price: 40,
    author: "Josephine Tey",
    description: "O Mistério dos Príncipes na Torre, de Josephine Tey.",
    photos: [
      { src: "/images/livros/livro-o-misterio-dos-principes-na-torre-josephine-tey-r-40/01.webp", alt: "O Mistério dos Príncipes na Torre - foto 1" },
      { src: "/images/livros/livro-o-misterio-dos-principes-na-torre-josephine-tey-r-40/02.webp", alt: "O Mistério dos Príncipes na Torre - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-o-que-resta-de-nos-virginie-grimaldi-r-30",
    title: "O Que Resta de Nós",
    category: "livros",
    price: 30,
    author: "Virginie Grimaldi",
    description: "O Que Resta de Nós, de Virginie Grimaldi.",
    photos: [
      { src: "/images/livros/livro-o-que-resta-de-nos-virginie-grimaldi-r-30/01.webp", alt: "O Que Resta de Nós - foto 1" },
      { src: "/images/livros/livro-o-que-resta-de-nos-virginie-grimaldi-r-30/02.webp", alt: "O Que Resta de Nós - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-o-que-tem-na-geladeira-rita-lobo-r-100",
    title: "O Que Tem na Geladeira?",
    category: "livros",
    price: 100,
    author: "Rita Lobo",
    description: "O Que Tem na Geladeira?, de Rita Lobo.",
    photos: [
      { src: "/images/livros/livro-o-que-tem-na-geladeira-rita-lobo-r-100/01.webp", alt: "O Que Tem na Geladeira? - foto 1" },
      { src: "/images/livros/livro-o-que-tem-na-geladeira-rita-lobo-r-100/02.webp", alt: "O Que Tem na Geladeira? - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-os-fantasmas-de-sheridan-le-fanu-sheridan-le-fanu-r-30",
    title: "Os Fantasmas de Sheridan Le Fanu",
    category: "livros",
    price: 30,
    author: "Sheridan Le Fanu",
    description: "Os Fantasmas de Sheridan Le Fanu, de Sheridan Le Fanu.",
    photos: [
      { src: "/images/livros/livro-os-fantasmas-de-sheridan-le-fanu-sheridan-le-fanu-r-30/01.webp", alt: "Os Fantasmas de Sheridan Le Fanu - foto 1" },
      { src: "/images/livros/livro-os-fantasmas-de-sheridan-le-fanu-sheridan-le-fanu-r-30/02.webp", alt: "Os Fantasmas de Sheridan Le Fanu - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-selecao-brasileira-de-gastronomia-alexandre-forbes-r-40",
    title: "Seleção Brasileira de Gastronomia",
    category: "livros",
    price: 40,
    author: "Alexandre Forbes",
    description: "Seleção Brasileira de Gastronomia, de Alexandre Forbes.",
    photos: [
      { src: "/images/livros/livro-selecao-brasileira-de-gastronomia-alexandre-forbes-r-40/01.webp", alt: "Seleção Brasileira de Gastronomia - foto 1" },
      { src: "/images/livros/livro-selecao-brasileira-de-gastronomia-alexandre-forbes-r-40/02.webp", alt: "Seleção Brasileira de Gastronomia - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-so-para-um-rita-lobo-r-50",
    title: "Só Para Um",
    category: "livros",
    price: 50,
    author: "Rita Lobo",
    description: "Só Para Um, de Rita Lobo.",
    photos: [
      { src: "/images/livros/livro-so-para-um-rita-lobo-r-50/01.webp", alt: "Só Para Um - foto 1" },
      { src: "/images/livros/livro-so-para-um-rita-lobo-r-50/02.webp", alt: "Só Para Um - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-til-eca-de-queiroz-rs20",
    title: "Til",
    category: "livros",
    price: 20,
    author: "Eça de Queiroz",
    description: "Til, de Eça de Queiroz.",
    photos: [
      { src: "/images/livros/livro-til-eca-de-queiroz-rs20/01.webp", alt: "Til - foto 1" },
      { src: "/images/livros/livro-til-eca-de-queiroz-rs20/02.webp", alt: "Til - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-trilogia-o-problema-dos-tres-corpos-cixin-liu-r-150",
    title: "Trilogia O Problema dos Três Corpos",
    category: "livros",
    price: 150,
    author: "Cixin Liu",
    description: "Trilogia O Problema dos Três Corpos, de Cixin Liu.",
    photos: [
      { src: "/images/livros/livro-trilogia-o-problema-dos-tres-corpos-cixin-liu-r-150/01.webp", alt: "Trilogia O Problema dos Três Corpos - foto 1" },
      { src: "/images/livros/livro-trilogia-o-problema-dos-tres-corpos-cixin-liu-r-150/02.webp", alt: "Trilogia O Problema dos Três Corpos - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-tudo-e-rio-carla-madeira-r-35",
    title: "Tudo é Rio",
    category: "livros",
    price: 35,
    author: "Carla Madeira",
    description: "Tudo é Rio, de Carla Madeira.",
    photos: [
      { src: "/images/livros/livro-tudo-e-rio-carla-madeira-r-35/01.webp", alt: "Tudo é Rio - foto 1" },
      { src: "/images/livros/livro-tudo-e-rio-carla-madeira-r-35/02.webp", alt: "Tudo é Rio - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-uma-familia-feliz-raphael-montes-r-35",
    title: "Uma Família Feliz",
    category: "livros",
    price: 35,
    author: "Raphael Montes",
    description: "Uma Família Feliz, de Raphael Montes.",
    photos: [
      { src: "/images/livros/livro-uma-familia-feliz-raphael-montes-r-35/01.webp", alt: "Uma Família Feliz - foto 1" },
      { src: "/images/livros/livro-uma-familia-feliz-raphael-montes-r-35/02.webp", alt: "Uma Família Feliz - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "livro-vespera-carla-madeira-r-35",
    title: "Véspera",
    category: "livros",
    price: 35,
    author: "Carla Madeira",
    description: "Véspera, de Carla Madeira.",
    photos: [
      { src: "/images/livros/livro-vespera-carla-madeira-r-35/01.webp", alt: "Véspera - foto 1" },
      { src: "/images/livros/livro-vespera-carla-madeira-r-35/02.webp", alt: "Véspera - foto 2" },
    ],
    seller: "mateus",
    sold: false,
  },
  {
    id: "vitrola-sony-ps-lx310bt-preta-r-1500",
    title: "Vitrola PS-LX310BT",
    category: "eletronicos",
    price: 1500,
    brand: "Sony",
    color: "Preta",
    tags: ["Bluetooth"],
    description: "Vitrola Sony PS-LX310BT, preta, com conexão Bluetooth.",
    photos: [
      { src: "/images/eletronicos/vitrola-sony-ps-lx310bt-preta-r-1500/01.webp", alt: "Vitrola PS-LX310BT - foto 1" },
      { src: "/images/eletronicos/vitrola-sony-ps-lx310bt-preta-r-1500/02.webp", alt: "Vitrola PS-LX310BT - foto 2" },
      { src: "/images/eletronicos/vitrola-sony-ps-lx310bt-preta-r-1500/03.webp", alt: "Vitrola PS-LX310BT - foto 3" },
      { src: "/images/eletronicos/vitrola-sony-ps-lx310bt-preta-r-1500/04.webp", alt: "Vitrola PS-LX310BT - foto 4" },
    ],
    seller: "mateus",
    sold: false,
  },
];

export function getListingsByCategory(slug: CategorySlug): Listing[] {
  return LISTINGS.filter((l) => l.category === slug);
}
